### ISSUE TITLE
FileSelectorWidget incompatible with FileSelector

### ISSUE THREAD

**Issue by psren** [MetaModels/attribute_file#21]
"Use filepicker without filetree"

If I now add an entry I get the following error in the Lightbox:

```php
Runtime notice: Declaration of MetaModels\Widgets\FileSelectorWidget::renderFiletree() should be compatible with Contao\FileSelector::renderFiletree($path, $intMargin, $mount = false, $blnProtected = false) in composer/vendor/metamodels/core/src/system/modules/metamodels/MetaModels/Widgets/FileSelectorWidget.php on line 26
#0 composer/vendor/metamodels/core/src/system/modules/metamodels/MetaModels/Widgets/FileSelectorWidget.php(26): __error(2048, 'Declaration of ...', '/vagrant/contao...', 26, Array)
#1 composer/vendor/composer/ClassLoader.php(363): include('/vagrant/contao...')
#2 composer/vendor/composer/ClassLoader.php(269): Composer\Autoload\includeFile('/vagrant/contao...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('MetaModels\Widg...')
#4 contao/file.php(103): spl_autoload_call('MetaModels\Widg...')
#5 contao/file.php(135): FilePicker->run()
#6 {main}
```

**Comment by discordier** [comment]
The metionend method has been removed since MetaModels/core@188a26db364adb708e2ac6c3fcce45410b150d92.
