### ISSUE TITLE
Too few arguments to build the query string

### ISSUE THREAD

**Issue by psren** [MetaModels/attribute_file#44]
Aktuellste Revision

Das passiert im Backend in der Liste des MetaModels bei dem ich ein File-Attribute einbunden habe.
Im Frontend passiert das auch.

```shell
Warning: strlen() expects parameter 1 to be string, array given in system/modules/core/library/Contao/Validator.php on line 284
#0 [internal function]: __error(2, 'strlen() expect...', '/kunden/302047_...', 284, Array)
#1 system/modules/core/library/Contao/Validator.php(284): strlen(Array)
#2 system/modules/core/library/Contao/Validator.php(268): Contao\Validator::isBinaryUuid(Array)
#3 system/modules/core/models/FilesModel.php(61): Contao\Validator::isUuid(Array)
#4 system/modules/core/models/FilesModel.php(44): Contao\FilesModel::findById(Array, Array)
#5 composer/vendor/metamodels/core/src/MetaModels/Helper/ToolboxFile.php(321): Contao\FilesModel::findByPk(Array)
#6 composer/vendor/metamodels/attribute_translatedfile/src/MetaModels/Attribute/TranslatedFile/TranslatedFile.php(84): MetaModels\Helper\ToolboxFile->addPathById(Array)
#7 composer/vendor/metamodels/core/src/MetaModels/Attribute/Base.php(433): MetaModels\Attribute\TranslatedFile\TranslatedFile->prepareTemplate(Object(MetaModels\Render\Template), Array, Object(MetaModels\Render\Setting\Simple))
#8 composer/vendor/metamodels/core/src/MetaModels/Item.php(115): MetaModels\Attribute\Base->parseValue(Array, 'html5', Object(MetaModels\Render\Setting\Simple))
#9 composer/vendor/metamodels/core/src/MetaModels/Item.php(463): MetaModels\Item->internalParseAttribute(Object(MetaModels\Attribute\TranslatedFile\TranslatedFile), 'html5', Object(MetaModels\Render\Setting\Collection))
#10 templates/reich/metamodel_unrendered_product.html5(34): MetaModels\Item->parseAttribute('download', 'html5', Object(MetaModels\Render\Setting\Collection))
#11 composer/vendor/metamodels/core/src/MetaModels/Render/Template.php(301): include('/kunden/302047_...')
#12 composer/vendor/metamodels/core/src/MetaModels/ItemList.php(814): MetaModels\Render\Template->parse('html5')
#13 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridList.php(105): MetaModels\ItemList->render('1', Object(MetaModels\FrontendIntegration\Module\ModelList))
#14 system/modules/core/classes/Hybrid.php(209): MetaModels\FrontendIntegration\HybridList->compile()
#15 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/MetaModelHybrid.php(99): Contao\Hybrid->generate()
#16 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridList.php(55): MetaModels\FrontendIntegration\MetaModelHybrid->generate()
#17 system/modules/core/elements/ContentModule.php(54): MetaModels\FrontendIntegration\HybridList->generate()
#18 system/modules/core/library/Contao/Controller.php(457): Contao\ContentModule->generate()
#19 system/modules/core/modules/ModuleArticle.php(187): Contao\Controller->getContentElement(Object(Contao\ContentModel), 'main')
#20 system/modules/core/modules/Module.php(139): Contao\ModuleArticle->compile()
#21 system/modules/core/modules/ModuleArticle.php(50): Contao\Module->generate()
#22 system/modules/core/library/Contao/Controller.php(393): Contao\ModuleArticle->generate(false)
#23 system/modules/core/library/Contao/Controller.php(255): Contao\Controller->getArticle(Object(Contao\ArticleModel), true, false, 'main')
#24 system/modules/core/pages/PageRegular.php(129): Contao\Controller->getFrontendModule('0', 'main')
#25 index.php(258): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#26 index.php(441): Index->run()
#27 {main}

Warning: strlen() expects parameter 1 to be string, array given in system/modules/core/library/Contao/Validator.php on line 305
#0 [internal function]: __error(2, 'strlen() expect...', '/kunden/302047_...', 305, Array)
#1 system/modules/core/library/Contao/Validator.php(305): strlen(Array)
#2 system/modules/core/library/Contao/Validator.php(268): Contao\Validator::isStringUuid(Array)
#3 system/modules/core/models/FilesModel.php(61): Contao\Validator::isUuid(Array)
#4 system/modules/core/models/FilesModel.php(44): Contao\FilesModel::findById(Array, Array)
#5 composer/vendor/metamodels/core/src/MetaModels/Helper/ToolboxFile.php(321): Contao\FilesModel::findByPk(Array)
#6 composer/vendor/metamodels/attribute_translatedfile/src/MetaModels/Attribute/TranslatedFile/TranslatedFile.php(84): MetaModels\Helper\ToolboxFile->addPathById(Array)
#7 composer/vendor/metamodels/core/src/MetaModels/Attribute/Base.php(433): MetaModels\Attribute\TranslatedFile\TranslatedFile->prepareTemplate(Object(MetaModels\Render\Template), Array, Object(MetaModels\Render\Setting\Simple))
#8 composer/vendor/metamodels/core/src/MetaModels/Item.php(115): MetaModels\Attribute\Base->parseValue(Array, 'html5', Object(MetaModels\Render\Setting\Simple))
#9 composer/vendor/metamodels/core/src/MetaModels/Item.php(463): MetaModels\Item->internalParseAttribute(Object(MetaModels\Attribute\TranslatedFile\TranslatedFile), 'html5', Object(MetaModels\Render\Setting\Collection))
#10 templates/reich/metamodel_unrendered_product.html5(34): MetaModels\Item->parseAttribute('download', 'html5', Object(MetaModels\Render\Setting\Collection))
#11 composer/vendor/metamodels/core/src/MetaModels/Render/Template.php(301): include('/kunden/302047_...')
#12 composer/vendor/metamodels/core/src/MetaModels/ItemList.php(814): MetaModels\Render\Template->parse('html5')
#13 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridList.php(105): MetaModels\ItemList->render('1', Object(MetaModels\FrontendIntegration\Module\ModelList))
#14 system/modules/core/classes/Hybrid.php(209): MetaModels\FrontendIntegration\HybridList->compile()
#15 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/MetaModelHybrid.php(99): Contao\Hybrid->generate()
#16 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridList.php(55): MetaModels\FrontendIntegration\MetaModelHybrid->generate()
#17 system/modules/core/elements/ContentModule.php(54): MetaModels\FrontendIntegration\HybridList->generate()
#18 system/modules/core/library/Contao/Controller.php(457): Contao\ContentModule->generate()
#19 system/modules/core/modules/ModuleArticle.php(187): Contao\Controller->getContentElement(Object(Contao\ContentModel), 'main')
#20 system/modules/core/modules/Module.php(139): Contao\ModuleArticle->compile()
#21 system/modules/core/modules/ModuleArticle.php(50): Contao\Module->generate()
#22 system/modules/core/library/Contao/Controller.php(393): Contao\ModuleArticle->generate(false)
#23 system/modules/core/library/Contao/Controller.php(255): Contao\Controller->getArticle(Object(Contao\ArticleModel), true, false, 'main')
#24 system/modules/core/pages/PageRegular.php(129): Contao\Controller->getFrontendModule('0', 'main')
#25 index.php(258): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#26 index.php(441): Index->run()
#27 {main}

Fatal error: Uncaught exception Exception with message Too few arguments to build the query string thrown in system/modules/core/library/Contao/Database/Statement.php on line 312
#0 system/modules/core/library/Contao/Database/Statement.php(249): Contao\Database\Statement->replaceWildcards(Array)
#1 system/modules/core/library/Contao/Model.php(944): Contao\Database\Statement->execute(Array)
#2 system/modules/core/library/Contao/Model.php(813): Contao\Model::find(Array)
#3 system/modules/core/models/FilesModel.php(66): Contao\Model::findOneBy('id', Array, Array)
#4 system/modules/core/models/FilesModel.php(44): Contao\FilesModel::findById(Array, Array)
#5 composer/vendor/metamodels/core/src/MetaModels/Helper/ToolboxFile.php(321): Contao\FilesModel::findByPk(Array)
#6 composer/vendor/metamodels/attribute_translatedfile/src/MetaModels/Attribute/TranslatedFile/TranslatedFile.php(84): MetaModels\Helper\ToolboxFile->addPathById(Array)
#7 composer/vendor/metamodels/core/src/MetaModels/Attribute/Base.php(433): MetaModels\Attribute\TranslatedFile\TranslatedFile->prepareTemplate(Object(MetaModels\Render\Template), Array, Object(MetaModels\Render\Setting\Simple))
#8 composer/vendor/metamodels/core/src/MetaModels/Item.php(115): MetaModels\Attribute\Base->parseValue(Array, 'html5', Object(MetaModels\Render\Setting\Simple))
#9 composer/vendor/metamodels/core/src/MetaModels/Item.php(463): MetaModels\Item->internalParseAttribute(Object(MetaModels\Attribute\TranslatedFile\TranslatedFile), 'html5', Object(MetaModels\Render\Setting\Collection))
#10 templates/reich/metamodel_unrendered_product.html5(34): MetaModels\Item->parseAttribute('download', 'html5', Object(MetaModels\Render\Setting\Collection))
#11 composer/vendor/metamodels/core/src/MetaModels/Render/Template.php(301): include('/kunden/302047_...')
#12 composer/vendor/metamodels/core/src/MetaModels/ItemList.php(814): MetaModels\Render\Template->parse('html5')
#13 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridList.php(105): MetaModels\ItemList->render('1', Object(MetaModels\FrontendIntegration\Module\ModelList))
#14 system/modules/core/classes/Hybrid.php(209): MetaModels\FrontendIntegration\HybridList->compile()
#15 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/MetaModelHybrid.php(99): Contao\Hybrid->generate()
#16 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridList.php(55): MetaModels\FrontendIntegration\MetaModelHybrid->generate()
#17 system/modules/core/elements/ContentModule.php(54): MetaModels\FrontendIntegration\HybridList->generate()
#18 system/modules/core/library/Contao/Controller.php(457): Contao\ContentModule->generate()
#19 system/modules/core/modules/ModuleArticle.php(187): Contao\Controller->getContentElement(Object(Contao\ContentModel), 'main')
#20 system/modules/core/modules/Module.php(139): Contao\ModuleArticle->compile()
#21 system/modules/core/modules/ModuleArticle.php(50): Contao\Module->generate()
#22 system/modules/core/library/Contao/Controller.php(393): Contao\ModuleArticle->generate(false)
#23 system/modules/core/library/Contao/Controller.php(255): Contao\Controller->getArticle(Object(Contao\ArticleModel), true, false, 'main')
#24 system/modules/core/pages/PageRegular.php(129): Contao\Controller->getFrontendModule('0', 'main')
#25 index.php(258): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#26 index.php(441): Index->run()
#27 {main}
```

Hier kommt der Fehler nicht mehr wenn ich diese Zeile in meinem Template auskommentiere.
```php
$item->parseAttribute('download', 'html5', $objRenderSetting)['raw']['value'];
```

**Comment by psren** [comment]
Also, das hat sich vermutlich hier eingeschlichen.
https://github.com/MetaModels/attribute_translatedfile/commit/9064aadf56eb66aa6797dd014ac03b6993b64f4f

Mit https://github.com/MetaModels/attribute_translatedfile/commit/f2f46f589af36fdeeaf96ad0c8f88f9cb6c533bd klappt es noch alles

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@psren could you please have a final look at this and tell if your issue has been resolved?
