### ISSUE TITLE
Encountered type string expected array

### ISSUE THREAD

**Issue by psren** [MetaModels/attribute_file#45]
Maybe related to #44 

```php
Fatal error: Uncaught exception LogicException with message Property logo (file) did not accept the value (The values differ. Encountered type string expected array (Found 'JuU��`��H' . "\0" . '>' . "\0" . '��', expected array ( 0 => 'JuU��`��H' . "\0" . '>' . "\0" . '��', ))). thrown in composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Model.php on line 178
#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(193): MetaModels\DcGeneral\Data\Model->setProperty('logo', Array)
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(225): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->reloadTree('file')
#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax.php(250): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->reloadFiletree(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(463): ContaoCommunityAlliance\DcGeneral\Controller\Ajax->executePostActions(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(122): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAjaxCall()
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(78): ContaoCommunityAlliance\DcGeneral\DC_General->checkAjaxCall()
#6 system/modules/core/classes/Backend.php(249): ContaoCommunityAlliance\DcGeneral\DC_General->__construct('mm_partners', Array)
#7 contao/main.php(137): Contao\Backend->getBackendModule('metamodel_mm_pa...')
#8 contao/main.php(288): Main->run()
#9 {main}
```

**Comment by cboelter** [comment]
@discordier Are working on a fix for that problems, we are working on a project and need it working :(

**Comment by discordier** [comment]
I hope I got it working now...

**Comment by cboelter** [comment]
@discordier the error is still there :( ...

```Fatal error: Uncaught exception InvalidArgumentException with message Invalid file array thrown in composer/vendor/metamodels/core/src/MetaModels/Helper/ToolboxFile.php on line 709```

**Comment by discordier** [comment]
You did update dcg and core and file?

**Comment by cboelter** [comment]
Yes I did composer update.

**Comment by discordier** [comment]
Damn... :(
The file picker widget is causing me to get bald... :/

**Comment by discordier** [comment]
@cboelter Have a look at https://github.com/MetaModels/core/commit/8f3a486fdf31fbe4910228e1b7c6ddb348892346

**Comment by cboelter** [comment]
If I do not select an file i get the error as before. If I add an file it works fine. But I can't remove the file it will be there after removing the file selection from file tree.

**Comment by design23** [comment]
Same here.

**Comment by cyberlussi** [comment]
With latest updates I can store an entry with no file, then select the file - store - works. But I cannot remove the file ("Auswahl aufheben"), the previous selected file stays in database.

**Comment by Hauge** [comment]
In der aktuellen Version von gestern Nachmittag kann ich speichern - jedoch kommt nach dem Speichern folgende Fehlermeldung (siehe https://github.com/MetaModels/core/issues/784 ):
```
/* Version 2 � 18-09-2014 This version is far more simplified than the first version. Thanks to a MetaMadels update it's much easier to modify the form data now! Thanks to Stefan Pr�ll by Design23 � http://www.design-23.de He helped me out to get this new version working. */
Fatal error: Uncaught exception InvalidArgumentException with message Invalid file array thrown in system/modules/metamodels/classes/src/MetaModels/Helper/ToolboxFile.php on line 714
```
Das einzige was aus dieser Zeit stammt ist der url-builder siehe:
```
Name                                             Version                 Last modification
============================================================================================
http://c-c-a.org/
contao-community-alliance/dc-general             dev-develop @ 853362    2015-03-24 05:07:21
contao-community-alliance/dependency-container   dev-develop @ 47f03a    2015-02-05 17:53:34
contao-community-alliance/event-dispatcher       dev-develop @ d2da54    2014-11-28 14:49:59
contao-community-alliance/events-contao-bindings dev-contao-3.2 @ 36eee0 2014-11-08 18:39:45
contao-community-alliance/translator             dev-develop @ 02feca    2014-06-05 08:57:37
--------------------------------------------------------------------------------------------

http://bit3.de
contao-community-alliance/meta-palettes          dev-master @ 13117d     2015-01-26 17:37:38
--------------------------------------------------------------------------------------------

https://www.cyberspectrum.de
discordier/justtextwidgets                       0.5.4                   2014-02-05 22:52:54
--------------------------------------------------------------------------------------------

http://www.doctrine-project.org
doctrine/cache                                   dev-master @ 6c5c32     2015-02-16 12:24:01
--------------------------------------------------------------------------------------------

http://www.leo-unglaub.net
leounglaub/contao-simple-ajax                    1.0.2                   2014-02-07 22:35:55
--------------------------------------------------------------------------------------------

http://www.men-at-work.de
menatwork/contao-multicolumnwizard               dev-dev @ ae91b5        2014-11-20 11:57:11
--------------------------------------------------------------------------------------------

http://now.metamodel.me/
metamodels/attribute_alias                       dev-tng @ 8ceb31        2015-01-29 17:36:33
metamodels/attribute_checkbox                    dev-tng @ e8cd5c        2015-01-30 09:07:10
metamodels/attribute_combinedvalues              dev-tng @ 6cc84e        2015-03-20 23:44:28
metamodels/attribute_country                     dev-tng @ b7bb7f        2015-01-29 18:01:21
metamodels/attribute_decimal                     dev-tng @ 439c58        2015-01-29 18:04:31
metamodels/attribute_file                        dev-tng @ 310e2c        2015-03-24 05:17:25
metamodels/attribute_langcode                    dev-tng @ 133458        2015-01-29 20:13:11
metamodels/attribute_longtext                    dev-tng @ c9e7d2        2015-01-29 20:59:06
metamodels/attribute_numeric                     dev-tng @ bec96d        2015-01-29 21:43:58
metamodels/attribute_rating                      dev-tng @ 741381        2015-01-30 00:22:15
metamodels/attribute_select                      dev-tng @ 31de9c        2015-03-21 06:26:52
metamodels/attribute_tabletext                   dev-tng @ 212e4c        2015-02-02 11:06:58
metamodels/attribute_tags                        dev-tng @ 308a1a        2015-03-24 11:46:44
metamodels/attribute_text                        dev-tng @ 3023cd        2015-01-30 05:34:20
metamodels/attribute_timestamp                   dev-tng @ 5e957a        2015-03-21 01:11:48
metamodels/attribute_translatedalias             dev-tng @ 3f68cd        2015-01-30 06:35:53
metamodels/attribute_translatedcheckbox          dev-tng @ 3813e4        2015-01-30 09:30:26
metamodels/attribute_translatedcombinedvalues    dev-tng @ 310be8        2015-02-03 17:59:19
metamodels/attribute_translatedfile              dev-tng @ db0526        2015-03-24 15:06:17
metamodels/attribute_translatedlongtext          dev-tng @ 52a3b7        2015-02-05 21:51:54
metamodels/attribute_translatedselect            dev-tng @ 575303        2015-02-18 02:05:09
metamodels/attribute_translatedtabletext         dev-tng @ e936db        2015-02-17 18:10:52
metamodels/attribute_translatedtags              dev-tng @ 10ec35        2015-02-18 01:41:47
metamodels/attribute_translatedtext              dev-tng @ 574459        2015-02-17 19:34:56
metamodels/attribute_url                         dev-tng @ 6e4d7b        2015-02-17 21:12:53
metamodels/bundle_all                            dev-master @ f58927     2013-10-01 20:03:31
metamodels/bundle_attributes                     dev-master @ 058e26     2014-02-03 14:19:34
metamodels/bundle_filter                         dev-master @ 45d9cf     2013-05-03 07:16:44
metamodels/bundle_nontranslated                  dev-master @ 5f2b3f     2014-02-17 14:37:26
metamodels/bundle_translated                     dev-master @ 4bc0c1     2014-02-17 14:34:39
metamodels/core                                  dev-tng @ 8f3a48        2015-03-24 11:01:56
metamodels/filter_checkbox                       dev-tng @ 7d06b8        2015-02-17 21:46:24
metamodels/filter_fromto                         dev-tng @ d84ea1        2015-03-19 08:13:52
metamodels/filter_range                          dev-tng @ 3516f5        2015-03-20 02:53:17
metamodels/filter_select                         dev-tng @ 597806        2015-01-10 05:37:20
metamodels/filter_tags                           dev-tng @ 1127e5        2015-02-18 01:59:32
metamodels/filter_text                           dev-tng @ 6df9de        2015-01-13 04:37:56
--------------------------------------------------------------------------------------------

http://pimple.sensiolabs.org
pimple/pimple                                    1.1.x-dev @ bc2fc1      2014-04-20 07:24:09
--------------------------------------------------------------------------------------------

http://symfony.com
symfony/event-dispatcher                         2.7.x-dev @ 186349      2015-03-13 17:50:01
symfony/expression-language                      2.7.x-dev @ 1ec5b5      2015-03-17 12:50:07
--------------------------------------------------------------------------------------------

other
contao-community-alliance/url-builder            dev-develop @ 5f8997    2014-09-20 03:38:06
```

**Comment by cboelter** [comment]
@discordier any news?

**Comment by cboelter** [comment]
With the following lines I fixed the error with no selected file.

```
if(!is_array($mixValues)) {
    return $mixValues;
 }
```
On this line https://github.com/MetaModels/attribute_file/blob/310e2c07957bebc2b9077acfda7dafc586c7f0a0/src/MetaModels/Attribute/File/File.php#L115

It does not fix the problem with deselecting a file :(

**Comment by cboelter** [comment]
@discordier i think i found another issue :( ...

```
Fatal error: Uncaught exception InvalidArgumentException with message Invalid file array thrown in composer/vendor/metamodels/core/src/MetaModels/Helper/ToolboxFile.php on line 714

#0 composer/vendor/metamodels/attribute_file/src/MetaModels/Attribute/File/File.php(115): MetaModels\Helper\ToolboxFile::convertValuesToDatabase(NULL)
#1 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(873): MetaModels\Attribute\File\File->serializeData(NULL)
```

I had a look on it, it seems that the serializeData() is called before the widgetToValue is called, so we dont have a valid array at this position.

**Comment by discordier** [comment]
How to end up there?

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@psren could you please have a final look at this and tell if your issue has been resolved?

**Comment by cyberlussi** [comment]
Closed?? Also ist für mich unverändert. Es kommt zwar keine Fehlermeldung mehr, aber ein bereits gewähltes Bild kann man aktuell nicht entfernen ("Auswahl ändern -> Auswahl entfernen")!!!

**Comment by discordier** [comment]
@cboelter,  @cyberlussi: ihr seid beide sicher auf dem aktuellsten tng?
Bei mir gibt es naemlich keine Probleme mehr.

**Comment by cboelter** [comment]
@discordier ja bin ich, in dem Dump von mir sollte das Problem auch bestehen!

**Comment by discordier** [comment]
alles klar.

**Comment by cyberlussi** [comment]
@discordier ja ich auch, immer per composer aktualisiert. ein bereits gewähltes Bild abwählen/leeren geht nicht, das alte bleibt.
contao/core 	3.2.20
contao-community-alliance/dc-general 	dev-develop (02c33c05)
metamodels/core 	dev-tng (8eaf7a7d)
metamodels/attribute_file 	dev-tng (310e2c07) (über bundle_attributes)

**Comment by Hauge** [comment]
Aktuelle nightly  hat den Fehler noch

**Comment by sevenfour66** [comment]
Das Problem besteht immer noch. Ein einmal gewähltes Bild/Datei lässt sich nicht mehr abwählen. Das alte Bild/Datei bleibt.

contao/core 3.4.4
contao-community-alliance/dc-general - 2.0.0-beta23
metamodels/core - dev-tng (1f4fd69b)
metamodels/attribute_file	- dev-tng (310e2c07)

**Comment by cyberlussi** [comment]
Ja, ich habe mal meine Installation geprüft - und da geht es nun, wie man es von Contao erwartet - ich kann ein Bild entfernen. Ich haben die letzten Monate nicht an dem Projekt gearbeitet und habe nur immer mal wieder den composer laufen lassen, aber es funktioniert nun.

contao/core 	3.2.20
contao-community-alliance/dc-general 	dev-develop (a69951db)
metamodels/core 	dev-tng (1f4fd69b)
metamodels/bundle_attributes 	1.0.1
--
metamodels/attribute_file 	dev-tng (310e2c07)
metamodels/attribute_translatedfile 	dev-tng (86e7eb3a)

Ich verwende keine Übersetzungen, so also attribute_file.

**Comment by sevenfour66** [comment]
Habe es gerade mit der aktuellen nightly auf einem Contao 3.4.3 getestet...gleiches Problem.

**Comment by inred-froehlich** [comment]
Gibt es hierfür schon einen Workaround?

**Comment by sevenfour66** [comment]
Würde mich auch interessieren ob es schon Neuigkeiten gibt.
